import { readdir } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import {
  COMPONENTS_DIR,
  CONFIG_FILE,
  GENERATED_DIR,
  NOTES_DIR,
} from "./paths";

/** Recursively collect files matching a predicate, returning absolute paths. */
async function walk(
  dir: string,
  match: (name: string) => boolean,
): Promise<string[]> {
  let entries: Awaited<ReturnType<typeof readdir>>;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return []; // directory may not exist yet
  }
  const out: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
      out.push(...(await walk(full, match)));
    } else if (match(entry.name)) {
      out.push(full);
    }
  }
  return out;
}

/** Turn an absolute path into a POSIX import specifier relative to GENERATED_DIR. */
function importSpecifier(absPath: string): string {
  let rel = relative(GENERATED_DIR, absPath).split(sep).join("/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

/** Derive the base slug + category segments + language from a note's path. */
function noteIdentity(
  absPath: string,
  locales: string[],
): { id: string; segments: string[]; lang: string | null } {
  const rel = relative(NOTES_DIR, absPath).split(sep).join("/");
  const withoutExt = rel.replace(/\.mdx$/, "");
  const parts = withoutExt.split("/");
  let fileSlug = parts.pop()!;
  const segments = parts;

  // Detect a language suffix: `getting-started.zh` -> slug "getting-started", lang "zh".
  let lang: string | null = null;
  const dot = fileSlug.lastIndexOf(".");
  if (dot > 0) {
    const suffix = fileSlug.slice(dot + 1);
    if (locales.includes(suffix)) {
      lang = suffix;
      fileSlug = fileSlug.slice(0, dot);
    }
  }

  // An `index.mdx` represents its parent folder.
  const id = fileSlug === "index" ? segments.join("/") : [...segments, fileSlug].join("/");
  return { id, segments, lang };
}

function toPascalCase(name: string): string {
  return name
    .replace(/\.[tj]sx?$/, "")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join("");
}

/**
 * Scan notes/ + components/ + config.ts and produce the source of the
 * generated manifest module that the client imports. This module statically
 * imports every note and user component so the bundler can tree-shake and
 * embed them into a single binary.
 */
export async function generateManifestSource(locales: string[] = []): Promise<string> {
  const noteFiles = (await walk(NOTES_DIR, (n) => n.endsWith(".mdx"))).sort();
  const componentFiles = (
    await walk(COMPONENTS_DIR, (n) => /\.[tj]sx?$/.test(n) && !n.startsWith("index."))
  ).sort();

  const lines: string[] = [
    "// AUTO-GENERATED by src/manifest.ts — do not edit by hand.",
    "/* eslint-disable */",
    `import config from "${importSpecifier(CONFIG_FILE)}";`,
    "",
  ];

  // --- Notes ---------------------------------------------------------------
  noteFiles.forEach((file, i) => {
    lines.push(`import * as note${i} from "${importSpecifier(file)}";`);
  });
  lines.push("");

  const noteEntries = noteFiles.map((file, i) => {
    const { id, segments, lang } = noteIdentity(file, locales);
    return `  {
    id: ${JSON.stringify(id)},
    segments: ${JSON.stringify(segments)},
    lang: ${JSON.stringify(lang)},
    module: note${i},
  }`;
  });

  lines.push("export const rawNotes = [");
  lines.push(noteEntries.join(",\n"));
  lines.push("];");
  lines.push("");

  // --- User components -----------------------------------------------------
  componentFiles.forEach((file, i) => {
    lines.push(`import * as userComp${i} from "${importSpecifier(file)}";`);
  });
  lines.push("");
  lines.push("export const userComponents: Record<string, any> = {};");
  componentFiles.forEach((file, i) => {
    const fallbackName = toPascalCase(file.split(sep).pop()!);
    // Register every named export, then map a bare `default` to the file name.
    lines.push(`Object.assign(userComponents, stripDefault(userComp${i}));`);
    lines.push(
      `if ("default" in userComp${i}) userComponents[${JSON.stringify(fallbackName)}] = (userComp${i} as any).default;`,
    );
  });
  lines.push("");
  lines.push(`function stripDefault(mod: Record<string, any>) {
  const { default: _omit, ...rest } = mod;
  return rest;
}`);
  lines.push("");

  lines.push("export { config };");

  return lines.join("\n") + "\n";
}

export async function writeManifest(
  locales: string[] = [],
): Promise<{ notes: number; components: number }> {
  const { mkdir, writeFile } = await import("node:fs/promises");
  await mkdir(GENERATED_DIR, { recursive: true });
  const source = await generateManifestSource(locales);
  await writeFile(join(GENERATED_DIR, "manifest.ts"), source, "utf8");

  const noteCount = (await walk(NOTES_DIR, (n) => n.endsWith(".mdx"))).length;
  const compCount = (
    await walk(COMPONENTS_DIR, (n) => /\.[tj]sx?$/.test(n) && !n.startsWith("index."))
  ).length;
  return { notes: noteCount, components: compCount };
}
